development:
  adapter: postgresql
  encoding: unicode
  database: select_worker_development
  pool: 5
  username: 
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: select_worker_test
  pool: 5
  username: 
  password: 
